name: Detect Merge
run-name: Detect Merge
on:
  pull_request:
    types: [closed]
defaults:
  run:
    shell: bash
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: pr-artifact

      - name: Read file
        run: cat pr.txt

      - name: Check if PR was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "PR was merged"
          else
            echo "PR was closed without merging"
          fi
