name: Run on PR
run-name: Run on PR
on:
  pull_request:
    types: [opened, synchronize]
defaults:
  run:
    shell: bash
jobs:
  test-download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: pr-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read file
        run: cat pr.txt
